name: Generate ASCII Art Work

on: push 

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4
            
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Generate ASCII Artwork
              run: cowsay -f elephant "Run away my Boy, I'm the Mighty Elephant....TRUMMM" >> Elephant.txt
            
            - name: Test file exists
              run: grep -i "Elephant" Elephant.txt
            
            - name: Read Elephant File
              run: cat Elephant.txt

            - name: List Repo Files
              run: ls -ltra