name: Generate ASCII Art Work

on: push 

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Chekout Repo
              uses: actions/checkout@v4
            
            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Generate ASCII Artwork
              run: cowsay -f Tiger "Run away my Boy, I'm the Mighty TIGER....ROAR" >> Tiger.txt
            
            - name: Test file exists
              run: grep -i "Tiger" Tiger.txt
            
            - name: Read Tiger File
              run: cat Tiger.txt

            - name: List Repo Files
              run: ls -ltra